#!/bin/bash

# Eliminar la extensión .ts del nombre del archivo
fileName=$(echo "$1" | sed 's/.ts//')

# Ejecutar ffmpeg con los nombres de archivo entre comillas
ffmpeg -i "$1" -c copy "$fileName.mp4"
